name: CD - Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - "Scraper Canasta"
      - "Scraper CER"
      - "Scraper Combustibles"
      - "Scraper ICC"
      - "Scraper ICL"
      - "Scraper ICL Adelanto"
      - "Scraper IPC"
      - "Scraper Personas"
      - "Scraper Rios"
      - "Scraper SMVM"
      - "Scraper UVA"
      - "Scraper UVI"
    types:
      - completed

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    uses: xlmriosx/shared-library/.github/workflows/AWS-Lambda-deploy.yml@main
    with:
      ecr-repository: "argly-api"
      function-name: "argly-function"
      aws-region: "sa-east-1"
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
